### ISSUE TITLE
Would you help provide more detailed steps to reproduce the training process?

### ISSUE THREAD

**Issue by ybdesire** [AI-Study-Han/Zero-Chatgpt#11]

**Comment by AI-Study-Han** [comment]
The data information and training code have already been provided; I'm not sure what additional details might still be needed on your side.

**Comment by ybdesire** [comment]
@AI-Study-Han Thanks for the reply. Would you share the link to download the file `ruozhiout_qa_cn.jsonl`  at code https://github.com/AI-Study-Han/Zero-Chatgpt/blob/main/data_process/data_process.py#L351 ?

**Comment by ybdesire** [comment]
@AI-Study-Han  And how to convert all processed json file (data_process.py output) to [pretrain.bin](https://huggingface.co/My521/Zero-Chatgpt/blob/main/pretrain.bin)?

**Comment by ybdesire** [comment]
> @AI-Study-Han And how to convert all processed json file (data_process.py output) to [pretrain.bin](https://huggingface.co/My521/Zero-Chatgpt/blob/main/pretrain.bin)?

Finally got that: https://github.com/AI-Study-Han/Zero-Chatgpt/blob/main/pretrain/generate_pretrain_data.py#L112

**Comment by AI-Study-Han** [comment]
> @AI-Study-Han Thanks for the reply. Would you share the link to download the file `ruozhiout_qa_cn.jsonl` at code https://github.com/AI-Study-Han/Zero-Chatgpt/blob/main/data_process/data_process.py#L351 ?

https://modelscope.cn/datasets/zhuangxialie/Llama3-Chinese-Dataset/resolve/master/ruozhiout_qa_cn.jsonl
