### ISSUE TITLE
Sir, what is the json file format for training?

### ISSUE THREAD

**Issue by mzb98** [AI-Study-Han/Zero-Chatgpt#3]
Sir, what is the json file format for training?   The path is  “./pretrain_data/pretrain_data_train.json“ .

**Comment by AI-Study-Han** [comment]
![image](https://github.com/user-attachments/assets/b45055cb-dacf-4550-9478-a270abb197bf)
Each line of the training data is a JSON object, with each object containing 'text' and 'source'. 'Text' represents the training text, and 'source' indicates the data source, which may be absent.

**Comment by mzb98** [comment]
Yes, I know. But my question is “data['text']“ how do I fill in the Q&A text?What is the format of data['text']?

**Comment by mzb98** [comment]
Yes,sir, I know .But What is the format of data['text']? How to fill in the Q&A information in data['text'].

**Comment by mzb98** [comment]
{ "text" : ""  ,"source":"" }
{ "text" : ""  ,"source":"" }
{ "text" : ""  ,"source":"" }

Like this format, if it's a question and answer message, how do I fill in the "text"

**Comment by mzb98** [comment]
Thanks you sir . I know what the problem is. For Q&A situations, I should use sft.py for fine tuning.
