### ISSUE TITLE
Sir, about the code to create the pretrain model. What is it？

### ISSUE THREAD

**Issue by mzb98** [AI-Study-Han/Zero-Chatgpt#6]
I found that the way I created, the output model was 600M in size, but yours was 300M.  I didn't change the parameters in the model.

**Comment by mzb98** [comment]
I found that the way I created, the output model was 600MB in size, but yours was 300MB. I didn't change the parameters in the model.

This is my code:

from transformers import AutoConfig, PreTrainedTokenizerFast
from safetensors.torch import save_file
import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from model import modeling_miaomiao
config_path = "./model"
config = AutoConfig.from_pretrained(config_path)
model = modeling_miaomiao.MiaomiaoForCausalLM(config)

save_directory = "./model"
state_dict = model.state_dict()
save_file(state_dict, f"{save_directory}/pretrain.safetensors")

**Comment by AI-Study-Han** [comment]
The size difference you're observing is likely due to the precision of the model weights. bf16 and float32

**Comment by mzb98** [comment]
Ok ,thank you sir.
